name: Java Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java sources
        run: |
          mkdir -p build/classes
          find src -name "*.java" > sources.txt
          javac -d build/classes @sources.txt

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: compiled-classes
          path: build/classes
