name: Java CI with Gradle Wrapper Update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Update Gradle Wrapper (if old version)
      run: |
        if [ -f ./gradlew ]; then
          ./gradlew wrapper --gradle-version 7.6
        else
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle wrapper --gradle-version 7.6
        fi

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/libs/
