name: Java CI with Gradle Wrapper Generation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Gradle (if gradlew is missing)
      run: |
        if [ ! -f ./gradlew ]; then
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle wrapper
        fi

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/libs/
